global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
  external_labels:
   servico: service-prometheus

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          grupo: "Prometheus"
  
  - job_name: ApiEasyBox
    scrape_interval: 5s
    scrape_timeout: 1s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["easybox:80"]
        labels:
          grupo: "webapi"

    